/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MyDataRouteImport } from './routes/my-data'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DatabasesRouteImport } from './routes/databases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmLlmidRouteImport } from './routes/llm.$llmid'
import { Route as DatabasesDatabaseIdRouteImport } from './routes/databases.$databaseId'
import { Route as AdminDataAccessRouteImport } from './routes/admin.data-access'
import { Route as AdminClassifiersRouteImport } from './routes/admin.classifiers'
import { Route as AdminChatsRouteImport } from './routes/admin.chats'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDataRoute = MyDataRouteImport.update({
  id: '/my-data',
  path: '/my-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesRoute = DatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmLlmidRoute = LlmLlmidRouteImport.update({
  id: '/llm/$llmid',
  path: '/llm/$llmid',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabasesDatabaseIdRoute = DatabasesDatabaseIdRouteImport.update({
  id: '/$databaseId',
  path: '/$databaseId',
  getParentRoute: () => DatabasesRoute,
} as any)
const AdminDataAccessRoute = AdminDataAccessRouteImport.update({
  id: '/admin/data-access',
  path: '/admin/data-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClassifiersRoute = AdminClassifiersRouteImport.update({
  id: '/admin/classifiers',
  path: '/admin/classifiers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatsRoute = AdminChatsRouteImport.update({
  id: '/admin/chats',
  path: '/admin/chats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/databases': typeof DatabasesRouteWithChildren
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/my-data': typeof MyDataRoute
  '/reset-password': typeof ResetPasswordRoute
  '/users': typeof UsersRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/classifiers': typeof AdminClassifiersRoute
  '/admin/data-access': typeof AdminDataAccessRoute
  '/databases/$databaseId': typeof DatabasesDatabaseIdRoute
  '/llm/$llmid': typeof LlmLlmidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/databases': typeof DatabasesRouteWithChildren
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/my-data': typeof MyDataRoute
  '/reset-password': typeof ResetPasswordRoute
  '/users': typeof UsersRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/classifiers': typeof AdminClassifiersRoute
  '/admin/data-access': typeof AdminDataAccessRoute
  '/databases/$databaseId': typeof DatabasesDatabaseIdRoute
  '/llm/$llmid': typeof LlmLlmidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/databases': typeof DatabasesRouteWithChildren
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/my-data': typeof MyDataRoute
  '/reset-password': typeof ResetPasswordRoute
  '/users': typeof UsersRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/classifiers': typeof AdminClassifiersRoute
  '/admin/data-access': typeof AdminDataAccessRoute
  '/databases/$databaseId': typeof DatabasesDatabaseIdRoute
  '/llm/$llmid': typeof LlmLlmidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/databases'
    | '/login'
    | '/manager'
    | '/my-data'
    | '/reset-password'
    | '/users'
    | '/admin/chats'
    | '/admin/classifiers'
    | '/admin/data-access'
    | '/databases/$databaseId'
    | '/llm/$llmid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/databases'
    | '/login'
    | '/manager'
    | '/my-data'
    | '/reset-password'
    | '/users'
    | '/admin/chats'
    | '/admin/classifiers'
    | '/admin/data-access'
    | '/databases/$databaseId'
    | '/llm/$llmid'
  id:
    | '__root__'
    | '/'
    | '/databases'
    | '/login'
    | '/manager'
    | '/my-data'
    | '/reset-password'
    | '/users'
    | '/admin/chats'
    | '/admin/classifiers'
    | '/admin/data-access'
    | '/databases/$databaseId'
    | '/llm/$llmid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatabasesRoute: typeof DatabasesRouteWithChildren
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  MyDataRoute: typeof MyDataRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UsersRoute: typeof UsersRoute
  AdminChatsRoute: typeof AdminChatsRoute
  AdminClassifiersRoute: typeof AdminClassifiersRoute
  AdminDataAccessRoute: typeof AdminDataAccessRoute
  LlmLlmidRoute: typeof LlmLlmidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-data': {
      id: '/my-data'
      path: '/my-data'
      fullPath: '/my-data'
      preLoaderRoute: typeof MyDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases': {
      id: '/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof DatabasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm/$llmid': {
      id: '/llm/$llmid'
      path: '/llm/$llmid'
      fullPath: '/llm/$llmid'
      preLoaderRoute: typeof LlmLlmidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databases/$databaseId': {
      id: '/databases/$databaseId'
      path: '/$databaseId'
      fullPath: '/databases/$databaseId'
      preLoaderRoute: typeof DatabasesDatabaseIdRouteImport
      parentRoute: typeof DatabasesRoute
    }
    '/admin/data-access': {
      id: '/admin/data-access'
      path: '/admin/data-access'
      fullPath: '/admin/data-access'
      preLoaderRoute: typeof AdminDataAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/classifiers': {
      id: '/admin/classifiers'
      path: '/admin/classifiers'
      fullPath: '/admin/classifiers'
      preLoaderRoute: typeof AdminClassifiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chats': {
      id: '/admin/chats'
      path: '/admin/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DatabasesRouteChildren {
  DatabasesDatabaseIdRoute: typeof DatabasesDatabaseIdRoute
}

const DatabasesRouteChildren: DatabasesRouteChildren = {
  DatabasesDatabaseIdRoute: DatabasesDatabaseIdRoute,
}

const DatabasesRouteWithChildren = DatabasesRoute._addFileChildren(
  DatabasesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatabasesRoute: DatabasesRouteWithChildren,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  MyDataRoute: MyDataRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UsersRoute: UsersRoute,
  AdminChatsRoute: AdminChatsRoute,
  AdminClassifiersRoute: AdminClassifiersRoute,
  AdminDataAccessRoute: AdminDataAccessRoute,
  LlmLlmidRoute: LlmLlmidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
