/** Stable API error codes — translated on the frontend via `apiErrors.<CODE>`. */
export const ErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
  REQUIRED_FIELDS_MISSING: 'REQUIRED_FIELDS_MISSING',
  INVALID_USER_ID: 'INVALID_USER_ID',
  INVALID_LLM_ID: 'INVALID_LLM_ID',
  INVALID_LLM_API_ID: 'INVALID_LLM_API_ID',
  INVALID_LLM_PRICE_ID: 'INVALID_LLM_PRICE_ID',
  INVALID_LLM_MODALITY_ID: 'INVALID_LLM_MODALITY_ID',
  INVALID_LLM_OR_LANGUAGE_CODE: 'INVALID_LLM_OR_LANGUAGE_CODE',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  PERMISSION_DENIED_API: 'PERMISSION_DENIED_API',
  PERMISSION_DENIED_PRICE: 'PERMISSION_DENIED_PRICE',
  PERMISSION_DENIED_MODALITY: 'PERMISSION_DENIED_MODALITY',
  PERMISSION_DENIED_LANGUAGE: 'PERMISSION_DENIED_LANGUAGE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',

  LLM_DELETE_NOT_ALLOWED: 'LLM_DELETE_NOT_ALLOWED',
  /** Model must be deactivated before it can be removed. */
  LLM_DELETE_STILL_ACTIVE: 'LLM_DELETE_STILL_ACTIVE',
  /** No LLM row for this id (e.g. already deleted). */
  LLM_DELETE_NOT_FOUND: 'LLM_DELETE_NOT_FOUND',
  /** FK: llm_api rows still reference this model. */
  LLM_DELETE_HAS_API: 'LLM_DELETE_HAS_API',
  /** FK: llm_price rows still reference this model. */
  LLM_DELETE_HAS_PRICING: 'LLM_DELETE_HAS_PRICING',
  /** FK: messages still reference this model as used_llm_id. */
  LLM_DELETE_REFERENCED_BY_MESSAGES: 'LLM_DELETE_REFERENCED_BY_MESSAGES',
  LLM_NAME_NOT_UNIQUE: 'LLM_NAME_NOT_UNIQUE',
  LLM_NAME_FORMAT_INVALID: 'LLM_NAME_FORMAT_INVALID',
  LLM_VERSION_FORMAT_INVALID: 'LLM_VERSION_FORMAT_INVALID',
  LLM_CONTEXT_LENGTH_INVALID: 'LLM_CONTEXT_LENGTH_INVALID',
  LLM_RELEASE_DATE_RANGE_INVALID: 'LLM_RELEASE_DATE_RANGE_INVALID',
  LLM_CREATED_AT_RANGE_INVALID: 'LLM_CREATED_AT_RANGE_INVALID',
  LLM_MODIFIED_AT_RANGE_INVALID: 'LLM_MODIFIED_AT_RANGE_INVALID',
  LLM_CREATED_BEFORE_MODIFIED_INVALID: 'LLM_CREATED_BEFORE_MODIFIED_INVALID',
  LLM_MAX_OUTPUT_TOKENS_INVALID: 'LLM_MAX_OUTPUT_TOKENS_INVALID',
  LLM_GROUP_INVALID_OR_FORBIDDEN: 'LLM_GROUP_INVALID_OR_FORBIDDEN',
  LLM_USER_REFERENCE_INVALID: 'LLM_USER_REFERENCE_INVALID',

  GLOBAL_INSTRUCTION_FIELD_REQUIRED: 'GLOBAL_INSTRUCTION_FIELD_REQUIRED',
  GLOBAL_INSTRUCTION_INVALID_TYPE: 'GLOBAL_INSTRUCTION_INVALID_TYPE',
  USER_INSTRUCTION_CONTENT_INVALID: 'USER_INSTRUCTION_CONTENT_INVALID',

  CHANGE_PASSWORD_FIELDS_REQUIRED: 'CHANGE_PASSWORD_FIELDS_REQUIRED',
  NEW_PASSWORD_TOO_SHORT: 'NEW_PASSWORD_TOO_SHORT',
  CURRENT_PASSWORD_WRONG_OR_USER_NOT_FOUND: 'CURRENT_PASSWORD_WRONG_OR_USER_NOT_FOUND',

  RESET_TOKEN_INVALID: 'RESET_TOKEN_INVALID',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',
  RESET_TOKEN_USED: 'RESET_TOKEN_USED',
  RESET_PASSWORD_FIELDS_REQUIRED: 'RESET_PASSWORD_FIELDS_REQUIRED',

  REPORT_TOO_SHORT: 'REPORT_TOO_SHORT',
  REPORT_TABLE_NOT_CONFIGURED: 'REPORT_TABLE_NOT_CONFIGURED',
  REPORT_CONTENT_INVALID: 'REPORT_CONTENT_INVALID',

  LOGIN_BODY_MISSING: 'LOGIN_BODY_MISSING',
  LOGIN_CREDENTIALS_MISSING: 'LOGIN_CREDENTIALS_MISSING',
  LOGIN_INVALID_CREDENTIALS: 'LOGIN_INVALID_CREDENTIALS',
  LOGIN_USER_ID_INVALID: 'LOGIN_USER_ID_INVALID',

  INVALID_CUSTOM_CHAT_INSTRUCTION: 'INVALID_CUSTOM_CHAT_INSTRUCTION',
  INVALID_CHAT_ID: 'INVALID_CHAT_ID',
  CHAT_TITLE_REQUIRED: 'CHAT_TITLE_REQUIRED',
  CHAT_TITLE_ALREADY_EXISTS: 'CHAT_TITLE_ALREADY_EXISTS',
  CHAT_NOT_FOUND: 'CHAT_NOT_FOUND',
  INVALID_CHAT_OR_MESSAGE_ID: 'INVALID_CHAT_OR_MESSAGE_ID',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_USED_LLM_ID: 'INVALID_USED_LLM_ID',

  CLASSIFIER_NOT_FOUND: 'CLASSIFIER_NOT_FOUND',
  CLASSIFIER_CODE_INVALID: 'CLASSIFIER_CODE_INVALID',
  CLASSIFIER_IN_USE: 'CLASSIFIER_IN_USE',
  CLASSIFIER_DUPLICATE: 'CLASSIFIER_DUPLICATE',

  ADMIN_CANNOT_DEACTIVATE_SELF: 'ADMIN_CANNOT_DEACTIVATE_SELF',
  LAST_ACTIVE_ADMIN_REQUIRED: 'LAST_ACTIVE_ADMIN_REQUIRED',
  ADMIN_CANNOT_DELETE_SELF: 'ADMIN_CANNOT_DELETE_SELF',

  NO_ACTIVE_LLM_API: 'NO_ACTIVE_LLM_API',
  /** Cannot activate (or mark active) an LLM without at least one active API key row. */
  LLM_ACTIVATE_REQUIRES_API: 'LLM_ACTIVATE_REQUIRES_API',
  /** Cannot remove data-access grants for the system ADMIN user group. */
  ADMIN_GROUP_ACCESS_PROTECTED: 'ADMIN_GROUP_ACCESS_PROTECTED',
  NO_DATABASES_ACCESSIBLE: 'NO_DATABASES_ACCESSIBLE',
  /** Another credential is already admin; client must confirm replace (body.confirm_replace_admin). */
  ADMIN_CREDENTIAL_REPLACE_CONFIRMATION_REQUIRED:
    'ADMIN_CREDENTIAL_REPLACE_CONFIRMATION_REQUIRED',
  /** Connection credential username must be unique per database (checked pre-encryption). */
  DATABASE_CREDENTIAL_USERNAME_DUPLICATE: 'DATABASE_CREDENTIAL_USERNAME_DUPLICATE',
  LLM_NOT_FOUND_OR_INACTIVE: 'LLM_NOT_FOUND_OR_INACTIVE',
  INVALID_CHAT_CONTENT: 'INVALID_CHAT_CONTENT',
  UNSUPPORTED_LLM_PROVIDER: 'UNSUPPORTED_LLM_PROVIDER',
  INVALID_MODEL_NAME: 'INVALID_MODEL_NAME',
  DATABASE_POOL_CONNECT_FAILED: 'DATABASE_POOL_CONNECT_FAILED',

  USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',

  /** Prevent duplicate price rows after DB unique constraint removal. */
  LLM_PRICE_DUPLICATE: 'LLM_PRICE_DUPLICATE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
